#!/usr/bin/env node
/**
 * Installs the git post-commit hook that auto-generates the changelog.
 *
 * Why post-commit (not pre-commit)?
 *   pre-commit runs BEFORE the commit exists, so the current message is missing
 *   and the first commit of the day finds "no commits today" and does nothing.
 *   post-commit runs AFTER the commit is created, sees today's full history,
 *   then amends the same commit with changelog files (or makes a follow-up
 *   commit if HEAD was already pushed).
 *
 * Run once after cloning:  node scripts/setup-hooks.js
 *   or via npm:            npm run setup-hooks
 * Also runs automatically on install via the "prepare" script.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const HOOKS_DIR = path.join(ROOT, '.git', 'hooks');
const POST_COMMIT = path.join(HOOKS_DIR, 'post-commit');
const PRE_COMMIT = path.join(HOOKS_DIR, 'pre-commit');

// ── Hook script content ────────────────────────────────────────────────────
// Uses POSIX sh so it works in Git Bash on Windows and bash on Linux/macOS.
const HOOK_CONTENT = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.js
# Regenerates changelog after every commit and folds it into the same commit.

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT" || exit 0

# Prevent infinite loop when we amend / auto-commit
if [ -n "$CHANGELOG_GENERATING" ]; then
  exit 0
fi

# Skip pure auto-changelog commits
subject="$(git log -1 --pretty=%s 2>/dev/null || true)"
case "$subject" in
  *"auto-update changelog"*|*"[skip changelog]"*)
    exit 0
    ;;
esac

export CHANGELOG_GENERATING=1

echo ""
echo "📋 Generating changelog..."
if ! node "$REPO_ROOT/scripts/generate-changelog.js"; then
  echo "⚠️  Changelog generator failed (commit was still created)."
  exit 0
fi

git add \\
  "$REPO_ROOT/public/changelog.json" \\
  "$REPO_ROOT/public/version.json"  \\
  "$REPO_ROOT/package.json"          \\
  2>/dev/null || true

if git diff --cached --quiet 2>/dev/null; then
  echo "ℹ️  Changelog already up to date."
  echo ""
  exit 0
fi

# Prefer amending so version + notes stay on the same feature commit.
# Only amend when HEAD is not already published on the remote tracking branch.
can_amend=1
if git rev-parse --abbrev-ref '@{u}' >/dev/null 2>&1; then
  # If HEAD is an ancestor of upstream, it was already pushed → do not rewrite.
  if git merge-base --is-ancestor HEAD '@{u}' 2>/dev/null; then
    can_amend=0
  fi
fi

if [ "$can_amend" = "1" ]; then
  git commit --amend --no-edit --no-verify
  echo "✅ Changelog amended into last commit."
else
  git commit -m "chore: auto-update changelog [skip ci]" --no-verify
  echo "✅ Changelog committed (HEAD was already on remote)."
fi
echo ""
`;

// ── Guards ────────────────────────────────────────────────────────────────
if (!fs.existsSync(path.join(ROOT, '.git'))) {
  // Soft-exit so "prepare" does not fail in CI tarballs / non-git installs
  console.log('ℹ️  No .git directory – skipping hook install.');
  process.exit(0);
}

if (!fs.existsSync(HOOKS_DIR)) {
  fs.mkdirSync(HOOKS_DIR, { recursive: true });
}

// ── Remove old pre-commit hook if it was ours ─────────────────────────────
if (fs.existsSync(PRE_COMMIT)) {
  try {
    const existing = fs.readFileSync(PRE_COMMIT, 'utf8');
    if (existing.includes('setup-hooks.js') || existing.includes('generate-changelog.js')) {
      fs.unlinkSync(PRE_COMMIT);
      console.log('🗑️  Old pre-commit changelog hook removed (now uses post-commit).');
    }
  } catch {
    // ignore
  }
}

// ── Write hook ─────────────────────────────────────────────────────────────
fs.writeFileSync(POST_COMMIT, HOOK_CONTENT, { encoding: 'utf8' });

try {
  fs.chmodSync(POST_COMMIT, '755');
} catch {
  // chmod may not work on Windows – git reads the hook anyway via sh
}

console.log('✅  Git post-commit hook installed at .git/hooks/post-commit');
console.log('📋  After every commit, the changelog will be generated and folded into the commit.');
console.log('💡  Make sure DEEPSEEK_API_KEY is set in .env.local (or .env).');
console.log('');
console.log('To run the changelog generator manually:');
console.log('  npm run changelog');
console.log('');
