#!/usr/bin/env node
/**
 * Installs the git pre-commit hook that auto-generates the changelog.
 * Changelog changes are staged into the same commit (no separate commit).
 *
 * Run once after cloning:  node scripts/setup-hooks.js
 *   or via npm:            npm run setup-hooks
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const HOOKS_DIR = path.join(ROOT, '.git', 'hooks');
const PRE_COMMIT = path.join(HOOKS_DIR, 'pre-commit');

// ── Hook script content ────────────────────────────────────────────────────
// Uses POSIX sh so it works in Git Bash on Windows and bash on Linux/macOS.
const HOOK_CONTENT = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.js
# Runs the QuorumFlow changelog generator before every commit.
# Changes are staged into the current commit (no separate commit).

REPO_ROOT="$(git rev-parse --show-toplevel)"

echo ""
echo "📋 Generating changelog..."
node "$REPO_ROOT/scripts/generate-changelog.js"

# Stage changelog files if they changed — they'll be part of this commit
git add \\
  "$REPO_ROOT/public/changelog.json" \\
  "$REPO_ROOT/public/version.json"  \\
  "$REPO_ROOT/package.json"          \\
  2>/dev/null || true

echo "✅ Changelog staged."
echo ""
`;

// ── Guards ────────────────────────────────────────────────────────────────
if (!fs.existsSync(path.join(ROOT, '.git'))) {
  console.error('❌  .git directory not found. Are you inside a git repository?');
  process.exit(1);
}

if (!fs.existsSync(HOOKS_DIR)) {
  fs.mkdirSync(HOOKS_DIR, { recursive: true });
}

// ── Remove old post-commit hook if it exists ──────────────────────────────
const POST_COMMIT = path.join(HOOKS_DIR, 'post-commit');
if (fs.existsSync(POST_COMMIT)) {
  fs.unlinkSync(POST_COMMIT);
  console.log('🗑️  Old post-commit hook removed.');
}

// ── Write hook ─────────────────────────────────────────────────────────────
fs.writeFileSync(PRE_COMMIT, HOOK_CONTENT, { encoding: 'utf8' });

try {
  fs.chmodSync(PRE_COMMIT, '755');
} catch {
  // chmod may not work on Windows – git reads the hook anyway via sh
}

console.log('✅  Git pre-commit hook installed at .git/hooks/pre-commit');
console.log('📋  Before every commit, the changelog will be updated and staged together.');
console.log('💡  Make sure DEEPSEEK_API_KEY is set in your .env file.');
console.log('');
console.log('To run the changelog generator manually:');
console.log('  npm run changelog');
console.log('');
