#!/usr/bin/env node
/**
 * Installs the git post-commit hook that auto-generates the changelog.
 *
 * Run once after cloning:  node scripts/setup-hooks.js
 *   or via npm:            npm run setup-hooks
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const HOOKS_DIR = path.join(ROOT, '.git', 'hooks');
const POST_COMMIT = path.join(HOOKS_DIR, 'post-commit');

// ── Hook script content ────────────────────────────────────────────────────
// Uses POSIX sh so it works in Git Bash on Windows and bash on Linux/macOS.
const HOOK_CONTENT = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.js
# Runs the QuorumFlow changelog generator after every commit.
# Uses a guard variable to prevent recursive hook calls.

# If this commit was already triggered by the hook itself, skip.
if [ "$CHANGELOG_HOOK_RUNNING" = "1" ]; then
  exit 0
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"

echo ""
node "$REPO_ROOT/scripts/generate-changelog.js"

# Check if any of the changelog files actually changed
CHANGED=$(git diff --name-only "$REPO_ROOT/public/changelog.json" "$REPO_ROOT/public/version.json" "$REPO_ROOT/package.json" 2>/dev/null)

if [ -n "$CHANGED" ]; then
  git add \\
    "$REPO_ROOT/public/changelog.json" \\
    "$REPO_ROOT/public/version.json"  \\
    "$REPO_ROOT/package.json"          \\
    2>/dev/null || true

  # Commit the changelog files with a skip-ci tag to avoid CI loops
  # The guard variable prevents this commit from re-triggering the hook
  CHANGELOG_HOOK_RUNNING=1 git commit -m "chore: auto-update changelog [skip ci]" --no-verify 2>/dev/null || true
fi
`;

// ── Guards ────────────────────────────────────────────────────────────────
if (!fs.existsSync(path.join(ROOT, '.git'))) {
  console.error('❌  .git directory not found. Are you inside a git repository?');
  process.exit(1);
}

if (!fs.existsSync(HOOKS_DIR)) {
  fs.mkdirSync(HOOKS_DIR, { recursive: true });
}

// ── Write hook ─────────────────────────────────────────────────────────────
fs.writeFileSync(POST_COMMIT, HOOK_CONTENT, { encoding: 'utf8' });

try {
  fs.chmodSync(POST_COMMIT, '755');
} catch {
  // chmod may not work on Windows – git reads the hook anyway via sh
}

console.log('✅  Git post-commit hook installed at .git/hooks/post-commit');
console.log('📋  After every commit, the changelog will be updated automatically.');
console.log('💡  Make sure DEEPSEEK_API_KEY is set in your .env file.');
console.log('');
console.log('To run the changelog generator manually:');
console.log('  npm run changelog');
console.log('');
