/* global importScripts */

// Attach Firebase Messaging background handlers to the real root service worker
// generated by next-pwa so push delivery uses the same worker the client registers.
importScripts('/firebase-messaging-sw.js');
